import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

import NavComp from "./(components)/NavComp";
import FooterComp from "./(components)/FooterComp";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "TEDxVITAP",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
        <Providers>
          <div>
            <NavComp/>
          </div>
          {children}

          <div>
            <FooterComp/>
          </div>
        </Providers>
      </body>
    </html>
  );
}
